### ISSUE TITLE
Investigate the capricious gate behavior where it does not want to see that the generator is VS 2019

### ISSUE THREAD

**Issue by anporumb** [Azure/macro-utils-c#52]
https://msazure.visualstudio.com/One/_build/results?buildId=36267895&view=logs&j=78934689-0812-53e3-e7b7-ea09dc100c75&t=78934689-0812-53e3-e7b7-ea09dc100c75

The above logs took 3 tries to persuade gate that Windows x64 is build with VS 2019... unknown reasons.

**Comment by dcristoloveanu** [comment]
Build does not exit anymore.
